### Register user
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "adi",
  "password" : "adi123",
  "name" : "adi"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "adi",
  "password" : "adi123"
}

### Get User
GET http://localhost:3000/api/users/current
Accept: application/json
X-API-TOKEN: 5ad4ba37-f078-406a-aaa4-be0dec11d417

### Logout User
DELETE http://localhost:3000/api/users/current
Accept: application/json
X-API-TOKEN: 8ced4df6-73a9-4353-9bcd-55f0dbb83cc9

### Update User
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "name" : "Eko Kurniawan"
}

### Update User Password
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "password" : "rahasia"
}

### Create Contact
POST http://localhost:3000/api/contacts
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 62189aa1-72fb-4088-9188-91885a7ec566

{
  "first_name" : "Budi Kurniawan",
  "last_name" : "Khannedy",
  "email": "eko@example.com",
  "phone" : "099123123213"
}

### Update Contact
PUT http://localhost:3000/api/contacts/48
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "first_name" : "Eko",
  "last_name" : "Khannedy",
  "email": "eko@example.com",
  "phone" : "099123123213"
}

### Get Contact
GET http://localhost:3000/api/contacts
Accept: application/json
X-API-TOKEN: 62189aa1-72fb-4088-9188-91885a7ec566

### Remove Contact
DELETE http://localhost:3000/api/contacts/128
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Search Contact
GET http://localhost:3000/api/contacts
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Add Address
POST http://localhost:3000/api/contacts/41/addresses
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "street" : "Jalan B",
  "city": "Jakarta",
  "province" : "DKI Jakarta",
  "country" : "Indonesia",
  "postal_code" : "13123"
}

### Get Address
GET http://localhost:3000/api/contacts/41/addresses/59
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Update Address
PUT http://localhost:3000/api/contacts/41/addresses/41
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "street" : "Jalan C",
  "city": "Bandung",
  "province" : "Jawa Barat",
  "country" : "Indonesia",
  "postal_code" : "34534"
}

### List Address
GET http://localhost:3000/api/contacts/41/addresses
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Remove Address
DELETE http://localhost:3000/api/contacts/41/addresses/59
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Create Theater
POST http://localhost:3000/api/theaters
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 0d3d00ce-3185-47db-8626-6f6fad0a715f

{
  "name" : "Theater 1",
  "location" : "Test",
  "capacity" : "250 Orang"
}

### get theater
GET http://localhost:3000/api/theaters/current
Accept: application/json
X-API-TOKEN: 4e605860-fc81-4c63-94bb-7503af8dc594

###
PATCH http://localhost:3000/api/theaters/305
Content-Type: application/json
X-API-TOKEN: bdb4498c-191b-414c-a622-c9ab811e7458

{
  "name" : "FX Sudirman"
}


### Remove Theater
DELETE http://localhost:3000/api/theaters/128
Accept: application/json
X-API-TOKEN: 403cbaf6-af16-4d58-b82a-ca9f81940a59


### Create Shows
POST http://localhost:3000/api/shows/2
Accept: application/json
Content-Type: multipart/form-data
X-API-TOKEN: 66aaac37-b1d5-426d-bdad-73e5e1eb88ed

{
    "title": "test",
    "description": "test",
    "duration": "25 test",
    "photo": "E:\\Project\\api-teater\\src\\img\\default\\1722416387341-wp2168910.jpg",
    "rating":"test",
    "theaterId" : 2        
}

### get shows
GET http://localhost:3000/api/shows/current
Accept: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

### get by Id
GET http://localhost:3000/api/shows/2/theaters/1
Accept: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

###
PATCH http://localhost:3000/api/shows/1/theaters/1
Content-Type: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

{
   "title": "coba"
}

### Remove shows
DELETE http://localhost:3000/api/shows/1
Accept: application/json
X-API-TOKEN: 317d003d-fc6b-4d30-9b7b-883f7df50fef


### Create Showtime
POST http://localhost:3000/api/showtimes/2
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

{
    "showTime" : "test"     
}

### get showstime
GET http://localhost:3000/api/showtimes/current
Accept: application/json
X-API-TOKEN: 278371ec-ef6d-4061-bd3e-7602c6361ec3

### get by Id
GET http://localhost:3000/api/showtimes/11
Accept: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

### Update Showtime
PATCH http://localhost:3000/api/showtimes/11
Content-Type: application/json
X-API-TOKEN: 278371ec-ef6d-4061-bd3e-7602c6361ec3

{
  "showId" : 2,
   "showTime": "coba"
}

### Remove Showtimes
DELETE http://localhost:3000/api/showtimes/8
Accept: application/json
X-API-TOKEN: 317d003d-fc6b-4d30-9b7b-883f7df50fef


### Create Ticket
POST http://localhost:3000/api/tickets
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 66aaac37-b1d5-426d-bdad-73e5e1eb88ed

{
  "seatNumber": "test",
  "photo": "test",
  "price": "test",
  "photo" : "test",
  "showId": 21,
  "contactId": 37
}

### get Ticket
GET http://localhost:3000/api/tickets/
Accept: application/json
X-API-TOKEN: 66aaac37-b1d5-426d-bdad-73e5e1eb88ed

### get ticket by Id
GET http://localhost:3000/api/tickets/3
Accept: application/json
X-API-TOKEN: 66aaac37-b1d5-426d-bdad-73e5e1eb88ed

### Update Ticket
PATCH http://localhost:3000/api/tickets/3
Content-Type: application/json
X-API-TOKEN: 66aaac37-b1d5-426d-bdad-73e5e1eb88ed

{
   "seatNumber": "ROW J",
   "showId" : 21
}

### Remove Tickets
DELETE http://localhost:3000/api/tickets/3
Accept: application/json
X-API-TOKEN: 66aaac37-b1d5-426d-bdad-73e5e1eb88ed