### Register user
POST http://localhost:3000/api/users
Content-Type: application/json
Accept: application/json

{
  "username": "adi",
  "password" : "adi123",
  "name" : "adi"
}

### Login User
POST http://localhost:3000/api/users/login
Content-Type: application/json
Accept: application/json

{
  "username": "adi",
  "password" : "adi123"
}

### Get User
GET http://localhost:3000/api/users/current
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

### Logout User
DELETE http://localhost:3000/api/users/current
Accept: application/json
X-API-TOKEN: 8ced4df6-73a9-4353-9bcd-55f0dbb83cc9

### Update User
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "name" : "Eko Kurniawan"
}

### Update User Password
PATCH http://localhost:3000/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "password" : "rahasia"
}

### Create Contact
POST http://localhost:3000/api/contacts
Accept: application/json
Content-Type: application/json
X-API-TOKEN: d826090a-9c91-4726-8a2b-9864dc3f8604

{
  "fullname" : "Adit Ganteng",
  "email": "eko@example.com",
  "phone" : "099123123213"
}

### Update Contact
PUT http://localhost:3000/api/contacts/48
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "fullname" : "Eko",
  "email": "eko@example.com",
  "phone" : "099123123213"
}

### Get Contact
GET http://localhost:3000/api/contacts
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

### Remove Contact
DELETE http://localhost:3000/api/contacts/67
Accept: application/json
X-API-TOKEN: 931a9050-ece8-4a06-9f8c-d1be3d10636c

### Search Contact
GET http://localhost:3000/api/contacts
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Add Address
POST http://localhost:3000/api/contacts/41/addresses
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "street" : "Jalan B",
  "city": "Jakarta",
  "province" : "DKI Jakarta",
  "country" : "Indonesia",
  "postal_code" : "13123"
}

### Get Address
GET http://localhost:3000/api/contacts/41/addresses/59
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Update Address
PUT http://localhost:3000/api/contacts/41/addresses/41
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

{
  "street" : "Jalan C",
  "city": "Bandung",
  "province" : "Jawa Barat",
  "country" : "Indonesia",
  "postal_code" : "34534"
}

### List Address
GET http://localhost:3000/api/contacts/41/addresses
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Remove Address
DELETE http://localhost:3000/api/contacts/41/addresses/59
Accept: application/json
X-API-TOKEN: 33acb47e-545b-4a2b-b27c-c0ba8196627f

### Create Theater
POST http://localhost:3000/api/theaters
Accept: application/json
Content-Type: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

{
  "name" : "Theater 1",
  "location" : "Test",
  "capacity" : "250 Orang"
}

### get theater
GET http://localhost:3000/api/theaters/1
Accept: application/json
X-API-TOKEN: 4e605860-fc81-4c63-94bb-7503af8dc594

###
PATCH http://localhost:3000/api/theaters/19
Content-Type: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

{
  "name" : "FX Sudirman"
}


### Remove Theater
DELETE http://localhost:3000/api/theaters/128
Accept: application/json
X-API-TOKEN: 403cbaf6-af16-4d58-b82a-ca9f81940a59


### Create Shows
POST http://localhost:3000/api/shows
Accept: application/json
Content-Type: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

{
    "title": "test",
    "description": "test",
    "duration": "25 test",
    "rating":"test",
    "theaterId" : 19      
}

### get shows
GET http://localhost:3000/api/shows/current
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

### get by Id
GET http://localhost:3000/api/shows/41
Accept: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

###
PATCH http://localhost:3000/api/shows/41
Content-Type: application/json
X-API-TOKEN: 3b5f7166-9ebd-499b-95ba-325f67e09adc

{
   "title": "coba",
   "description": "test",
  "duration": "test",
  "rating": "test"

}

### Remove shows
DELETE http://localhost:3000/api/shows/39
Accept: application/json
X-API-TOKEN: 317d003d-fc6b-4d30-9b7b-883f7df50fef


### Create Showtime
POST http://localhost:3000/api/showtimes
Accept: application/json
Content-Type: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

{
    "showTime" : "test",
    "showDate" : "2024-07-27T00:00:00Z",
    "showId" : 13
}

### get showstime
GET http://localhost:3000/api/showtimes/current
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

### get by Id
GET http://localhost:3000/api/showtimes/7
Accept: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

### Update Showtime
PATCH http://localhost:3000/api/showtimes/7
Content-Type: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7

{
  "showId" : 13,
   "showTime": "coba"
}

### Remove Showtimes
DELETE http://localhost:3000/api/showtimes/8
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7


### Create Ticket
POST http://localhost:3000/api/tickets
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

{
  "seatNumber": "test",
  "photo": "test",
  "price": 200000,
  "photo" : "test",
  "showId": 13,
  "contactId": 175
}

### get Ticket
GET http://localhost:3000/api/tickets/
Accept: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

### get ticket by Id
GET http://localhost:3000/api/tickets/10
Accept: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

### Update Ticket
PATCH http://localhost:3000/api/tickets/7
Content-Type: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

{
   "seatNumber": "ROW J",
   "showId" : 13
}

### Remove Tickets
DELETE http://localhost:3000/api/tickets/9
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7



### Create Orders
POST http://localhost:3000/api/orders
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

{  
    "amount": 50000,
    "status": "pending",
    "ticketId": 10
}

### get Orders
GET http://localhost:3000/api/orders/
Accept: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

### get ticket by Id
GET http://localhost:3000/api/orders/2
Accept: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

### Update Orders
PATCH http://localhost:3000/api/orders/7
Content-Type: application/json
X-API-TOKEN: 72743c08-c3b4-4e7e-8f21-3c3afae58357

{
   "seatNumber": "ROW J",
   "showId" : 13
}

### Remove Orders
DELETE http://localhost:3000/api/orders/9
Accept: application/json
X-API-TOKEN: c9d88e2e-cc31-4cbc-ac80-e793ac2acad7